### ISSUE TITLE
Make relevant Database scheme considering our requirements

### ISSUE THREAD

**Issue by aman247av** [aman247av/Mess-Management-System-IIITG#1]
--> User Auth
--> Menu (whole) & (daily)
--> Complaint (register, tracking and mapping with user)
--> Order History (mapping with user)
--> Canteen Item menu
--> transaction table if needed

Last three are future implementation.

**Comment by aman247av** [comment]
We are going with MySQL as there are too many relations, please suggest why we should go with mongodb (if you think)

**Comment by abhisheksingh789** [comment]
> We are going with MySQL as there are too many relations, please suggest why we should go with mongodb (if you think)

yes , you should use combination of sql and mongo for better engagement of project
